#ifndef LevelOptimizer_hpp
#define LevelOptimizer_hpp

#include <Geode/Geode.hpp>
#include <vector>

using namespace geode::prelude;

/**
 * LevelOptimizer handles the automated cleanup and performance 
 * optimization of procedural levels generated by Co Engine.
 */
class LevelOptimizer {
public:
    // Global Accessor (Singleton)
    static LevelOptimizer* sharedState();

    // 1. Core Cleanup: Scans the editor for redundant geometry and artifacts
    void runOptimizationPass(LevelEditorLayer* editor);

    // 2. Auto-LDM Compiler: Identifies high-density decoration and manages LDM status
    void compileLDMPreset(LevelEditorLayer* editor);

    // 3. Collision Density Check: Checks if the object count in a 500x500 area
    // exceeds safe thresholds, providing a 'density map' for the generator
    int calculateAreaDensity(LevelEditorLayer* editor, CCPoint center, float radius);

    // 4. Cleanup Triggers: Purges broken or orphan triggers
    void purgeBrokenTriggers(LevelEditorLayer* editor);

private:
    // Private constructor for Singleton pattern
    LevelOptimizer() {}

    // Helper: Logic to determine if an object is purely decorative 
    // (Used to decide if it should be removed or hidden in LDM)
    bool isObjectDecorative(GameObject* obj);

    // Internal state for optimization results
    int m_lastRemovedCount = 0;
};

#endif /* LevelOptimizer_hpp */
