name: Build Co Engine

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: Win64,     os: windows-latest, target: Win64,     platform: win }
          - { name: Android32, os: ubuntu-latest,  target: Android32, platform: android }
          - { name: Android64, os: ubuntu-latest,  target: Android64, platform: android }
          - { name: macOS,     os: macos-latest,   target: macOS,     platform: mac }
          - { name: iOS,       os: macos-latest,   target: iOS,       platform: ios }

    steps:
      - uses: actions/checkout@v4

      - name: Build Geode Mod
        run: geode build --platform ${{ matrix.platform }}
